=== SanchezMarioo/DAM/1-DAM/Lenguajes de Marcas/XML/XSD/Ejer10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Titulo" type="xs:string"/>
        <xs:element ref="Contenido"/>
        <xs:element name="Copyright" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Contenido">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
          <xs:element ref="Capitulo" maxOccurs="unbounded"/>
          <xs:element ref="Separacion" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Capitulo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Tema" type="xs:string"/>
        <xs:element ref="Seccion" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="materia" default="Java">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="XML"/>
            <xs:enumeration value="Java"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Separacion">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Seccion">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="apartados" type="xs:string" use="required"/>
          <xs:attribute name="dificil" default="no">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="si"/>
                <xs:enumeration value="no"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== SanchezMarioo/DAM/1-DAM/Lenguajes de Marcas/XML/XSD/Ejer10.xml
<?xml version="1.0" encoding="UTF-8"?>
<Libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejer10.xsd">
  <Titulo>Pepe</Titulo>
  <Contenido>
    <Capitulo materia="XML">
      <Tema>Ficcion</Tema>
      <Seccion apartados="si">Secion II</Seccion>
    </Capitulo>
    <Capitulo>
      <Tema>Otro tema</Tema>
      <Seccion apartados="no">Seccion III</Seccion>
    </Capitulo>
    <Separacion/>
  </Contenido>
  <Copyright>ASVDS</Copyright>
</Libro>
