=== SanchezMarioo/DAM/1-DAM/Lenguajes de Marcas/Repaso_Examen_XML_XPath/Seguros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="numero">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[9]{1}[0-9]{7,8}"/>
      </xs:restriction>
    </xs:simpleType>
    
    
  </xs:element>
  <xs:element name="poliza">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="numero" />
        <xs:element name="tomador" type="xs:string"/>
        <xs:element name="asegurado" type="TipoAsegurado" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="externa" type="xs:string" use="optional"/>
    </xs:complexType>
  </xs:element>
  
  
  <xs:complexType name="TipoAsegurado">
    <xs:sequence>
      <xs:element name="garantia" type="TipoGarantia" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="nombre" type="xs:string" use="required" />
    <xs:attribute name="apellidos" type="xs:string" use="required" />
  </xs:complexType>
  
  
  <xs:complexType name="TipoGarantia">
    <xs:sequence>
      <xs:element ref="tipo" />
      <xs:element name="capital" type="xs:int" />
    </xs:sequence>
    <xs:attribute name="vigor" type="xs:string" use="required" />
  </xs:complexType>
  <xs:element name="capital" type="xs:int" >
    <xs:simpleType>
      <xs:restriction>
        
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="envio">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="poliza"  maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tipo">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Vida" />
        <xs:enumeration value="Accidentes" />
        <xs:enumeration value="Dental" />
        <xs:enumeration value="Viaje" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== SanchezMarioo/DAM/1-DAM/Lenguajes de Marcas/Repaso_Examen_XML_XPath/Seguros.xml
<?xml version="1.0" encoding="UTF-8"?>
<envio xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/1-DAM/Lenguajes%20de%20Marcas/Repaso_Examen_XML_XPath/Seguros.xsd">
  <poliza>
    <numero>99000000</numero>
    <tomador>Manuel Gonzalez Sanchez</tomador>
    <asegurado nombre="Carlos" apellidos="Sanchez">
      <garantia vigor="S">
        <tipo>Accidentes</tipo>
        <capital>10000</capital>
      </garantia>
      <garantia vigor="S">
        <tipo>Dental</tipo>
        <capital>500</capital>
      </garantia>
    </asegurado>
    <asegurado nombre="Juan" apellidos="López">
      <garantia vigor="N">
        <tipo>Vida</tipo>
        <capital>60000</capital>
      </garantia>
    </asegurado>
  </poliza>
  <poliza externa="S">
    <numero>99000001</numero>
    <tomador>Pedro Martin Gomez</tomador>
    <asegurado nombre="Pedro" apellidos="Martin">
      <garantia vigor="S">
        <tipo>Vida</tipo>
        <capital>80000</capital>
      </garantia>
    </asegurado>
  </poliza>
  <poliza>
    <numero>99000002</numero>
    <tomador>Alfredo Salas Perez</tomador>
    <asegurado nombre="Lucas" apellidos="Montero">
      <garantia vigor="S">
        <tipo>Vida</tipo>
        <capital>90000</capital>
      </garantia>
    </asegurado>
    <asegurado nombre="Carmen" apellidos="Sanchez"></asegurado>
    <asegurado nombre="Maria" apellidos="Fernandez">
      <garantia vigor="S">
        <tipo>Vida</tipo>
        <capital>90000</capital>
      </garantia>
      <garantia vigor="N">
        <tipo>Accidentes</tipo>
        <capital>4000</capital>
      </garantia>
      <garantia vigor="S">
        <tipo>Dental</tipo>
        <capital>300</capital>
      </garantia>
    </asegurado>
  </poliza>
</envio>
