=== SanchezMarioo/DAM/1-DAM/Lenguajes de Marcas/Repaso_Examen_XML_XPath/Universidad.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="nombre" type="xs:string"/>
  <xs:element name="edad" type="xs:int" />
  <xs:element name="nota" type="TipoNota" >
  
  
    <xs:complexType name="TipoNota">
      <xs:simpleContent>
        <xs:extension>
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:fractionDecimal value="2"/>
            </xs:restriction>
          </xs:simpleType>
          <xs:attribute name="media" type="xs:int" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:int">
                <xs:minInclusive value="10"/>
                <xs:maxInclusive value="20" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  
  <xs:element name="universidad">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="alumno" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="edad" />
        <xs:element ref="nota" />
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>  
  
</xs:schema>

=== SanchezMarioo/DAM/1-DAM/Lenguajes de Marcas/Repaso_Examen_XML_XPath/Universidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/1-DAM/Lenguajes%20de%20Marcas/Repaso_Examen_XML_XPath/Universidad.xsd">
  <alumno id="A1">
    <nombre>Laura</nombre>
    <edad>21</edad>
    <nota media="10">8.75</nota>
  </alumno>
  <alumno id="A2">
    <nombre>Carlos</nombre>
    <edad>19</edad>
    <nota media="20">6.50</nota>
  </alumno>
</universidad>
