=== SanchezMarioo/DAM/1-DAM/Lenguajes de Marcas/Repaso_Examen_XML_XPath/Universidad2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="nombre" type="xs:string"/>
  <xs:element name="universidad">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="facultad" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="facultad">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="curso" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="tipoCodigoFacultad" />
    </xs:complexType>
  </xs:element>
    <xs:simpleType name="tipoCodigoFacultad">
    <xs:restriction base="xs:string">
      <xs:pattern value="F[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="curso">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="creditos"/>
        <xs:element ref="profesor"/>
        <xs:element ref="alumno" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="tipoCodigoCurso"/>
      <xs:attribute name="activo" type="tipoActivo" default="S" use="optional"/>
    </xs:complexType>
  </xs:element>
      <xs:simpleType name="tipoActivo">
      <xs:restriction base="xs:string">
        <xs:enumeration value="S"/>
        <xs:enumeration value="N"/>
      </xs:restriction>
    </xs:simpleType>
  <xs:simpleType name="tipoCodigoCurso">
    <xs:restriction base="xs:string">
      <xs:pattern value="CS[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>
    <xs:element name="creditos">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="12"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="profesor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="departamento"/>
      </xs:sequence>
      <xs:attribute name="id" type="tipoCodigoProfesor"/>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="tipoCodigoProfesor">
    <xs:restriction base="xs:string">
      <xs:pattern value="P[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="departamento" type="xs:string"/>
  <xs:element name="alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="nota"/>
      </xs:sequence>
      <xs:attribute name="dni" type="tipoDNI" />
    </xs:complexType>
  </xs:element>
    <xs:simpleType name="tipoDNI">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{8}[A-Z]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="nota">
    <xs:simpleType>
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="10"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
</xs:schema>

=== SanchezMarioo/DAM/1-DAM/Lenguajes de Marcas/Repaso_Examen_XML_XPath/Universidad2.xml
<?xml version="1.0" encoding="UTF-8"?>
<universidad xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/1-DAM/Lenguajes%20de%20Marcas/Repaso_Examen_XML_XPath/Universidad2.xsd">
  <facultad codigo="F01">
    <nombre>Ingeniería</nombre>
    <curso codigo="CS01" activo="S">
      <nombre>Programación</nombre>
      <creditos>6</creditos>
      <profesor id="P01">
        <nombre>Laura Gómez</nombre>
        <departamento>Informática</departamento>
      </profesor>
      <alumno dni="12345678A">
        <nombre>Juan García</nombre>
        <nota>8</nota>
      </alumno>
      <alumno dni="87654321B">
        <nombre>Ana López</nombre>
        <nota>6</nota>
      </alumno>
    </curso>
    <curso codigo="CS02" activo="N">
      <nombre>Bases de Datos</nombre>
      <creditos>5</creditos>
      <profesor id="P02">
        <nombre>Carlos Ruiz</nombre>
        <departamento>Datos</departamento>
      </profesor>
      <alumno dni="11223344C">
        <nombre>Pedro Martín</nombre>
        <nota>9</nota>
      </alumno>
    </curso>
  </facultad>
  <facultad codigo="F02">
    <nombre>Humanidades</nombre>
    <curso codigo="CS03">
      <nombre>Historia</nombre>
      <creditos>4</creditos>
      <profesor id="P03">
        <nombre>María López</nombre>
        <departamento>Historia</departamento>
      </profesor>
      <alumno dni="99887766D">
        <nombre>Lucía Fernández</nombre>
        <nota>7</nota>
      </alumno>
    </curso>
  </facultad>
</universidad>
